### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by rosheen33** [aliafshar/a8#17] opened 2015-08-27 06:15 UTC
Traceback (most recent call last):
  File "/usr/local/bin/a8", line 9, in <module>
    load_entry_point('a8==0.11', 'console_scripts', 'a8')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/a8/__main__.py", line 9, in <module>
    from a8 import app
  File "/usr/local/lib/python2.7/dist-packages/a8/app.py", line 12, in <module>
    from a8 import (terminals, files, buffers, vimembed, window, config, bookmarks,
  File "/usr/local/lib/python2.7/dist-packages/a8/terminals.py", line 11, in <module>
    import psutil, psutil.error
ImportError: No module named error

**Comment by rosheen33** [comment] 2015-08-27 06:15
current working directory
  = ~/Downloads/a8-master/a8

**Comment by rosheen33** [comment] 2015-08-27 06:17
this error occur after I type a8 in terminal

**Comment by dbarnett** [comment] 2015-08-27 08:14
Dupe of #11. You'll need to run from the git HEAD version for the time being.

**Closed by dbarnett** 2015-08-27 08:14 UTC
